package org.myProject.alcheAPIPrototype;

/**12 Categories**/
public enum Category {
	ARTS_ENTERTAINMENT,
	BUSINESS,
	COMPUTERS_INTERNET,
	CULTURE_POLITICS,
	GAMING,
	HEALTH,
	LAW_CRIME,
	RELIGION,
	RECREATION,
	SCIENCE_TECHNOLOGY,
	SPORTS,
	WEATHER
}
